/**
 * interpret-checkin — Supabase Edge Function
 *
 * Receives body zones + free text from user, returns 3-5 emotion options
 * generated by GPT-4o-mini. Each option includes a canonical EmotionKey
 * so the frontend can apply the correct color/icon without text-parsing.
 *
 * T-V7: GPT label normalization
 *   Every option now includes `key: EmotionKey` — one of 8 canonical values.
 *   The Edge Function maps Spanish GPT output → EmotionKey here (single source of truth).
 *   The frontend (reflect.tsx) can use `option.key` directly for colors.
 *
 * Endpoint: POST /functions/v1/interpret-checkin
 * Body: { zones: string[], notes: string }
 * Response: { options: EmotionOption[], crisis_flag: boolean, source: "ai"|"mock"|"error" }
 *
 * Safety filter (T-C2): detects crisis signals in user notes AND GPT output.
 * Language rules: tentative Spanish ("¿Podría ser...?") — never assertive.
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import OpenAI from "https://deno.land/x/openai@v4.24.1/mod.ts";

// ── CORS ────────────────────────────────────────────────────────────────────
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

// ── T-V7: Canonical emotion keys ────────────────────────────────────────────
/**
 * 8 canonical emotion keys used throughout the app.
 * These values are shared between this Edge Function and the frontend.
 * Source of truth for EmotionColors in constants/colors.ts.
 *
 * Clinical basis: ASD Level 1 interoceptive awareness model
 * (Mahler 2015; Craig 2015; Kinnaird et al. 2019 — alexithymia in 50–85% of autistic adults)
 */
type EmotionKey =
  | "calm"
  | "anxious"
  | "overwhelmed"
  | "sad"
  | "tired"
  | "joyful"
  | "irritable"
  | "unnamed";

/** Spanish label fragments that map to each canonical key */
const EMOTION_KEY_MAP: Record<EmotionKey, string[]> = {
  calm:        ["calma", "calmado", "tranquil", "paz", "sereno", "relajad", "equilibr"],
  anxious:     ["ansied", "ansios", "nervios", "preocup", "inquiet", "intranquil", "tenso", "tension"],
  overwhelmed: ["saturd", "abrumad", "sobrecarg", "desbord", "agotamiento sensorial", "sobrestimul"],
  sad:         ["tristeza", "triste", "melancol", "pena", "abatid", "dolor emocional"],
  tired:       ["cansancio", "cansad", "agotad", "fatiga", "fatigad", "sin energía", "sin energia", "extenuad"],
  joyful:      ["alegr", "feliz", "felicidad", "bienestar", "content", "entusiasmo", "entusiasmad", "energizad"],
  irritable:   ["irritabil", "irritad", "frustrac", "frustrad", "molest", "tensión muscular", "tension muscular", "agitad"],
  unnamed:     ["sin nombre", "no tiene nombre", "indescriptib", "sin categor", "algo que", "difícil de nombrar", "dificil de nombrar"],
};

/**
 * Maps a Spanish GPT label to the closest canonical EmotionKey.
 * Uses substring matching against known keyword fragments.
 * Falls back to "unnamed" if no match found (valid state — alexithymia).
 */
function normalizeToEmotionKey(label: string): EmotionKey {
  const normalized = label
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, ""); // remove accents for matching

  for (const [key, fragments] of Object.entries(EMOTION_KEY_MAP) as [EmotionKey, string[]][]) {
    if (fragments.some((fragment) => normalized.includes(fragment))) {
      return key;
    }
  }

  // No match — valid for alexithymia states or creative GPT labels
  return "unnamed";
}

// ── Types ───────────────────────────────────────────────────────────────────
type EmotionOption = {
  label: string;       // Spanish display label from GPT
  key: EmotionKey;     // T-V7: canonical key for colors/icons
  description: string; // Tentative 1-2 sentence description
  confidence: "alta" | "media" | "baja";
};

type ResponseBody = {
  options: EmotionOption[];
  crisis_flag: boolean;
  source: "ai" | "mock" | "error";
};

// ── System Prompt ───────────────────────────────────────────────────────────
/**
 * Guides GPT to use emotion labels that map cleanly to our canonical keys.
 * The label list in the prompt aligns with EMOTION_KEY_MAP fragments above.
 */
const SYSTEM_PROMPT = `Eres un asistente especializado en apoyar a personas con TEA Nivel 1
a identificar y nombrar sus experiencias emocionales y sensoriales.

Tu rol es proponer posibilidades, NO diagnosticar ni afirmar.

ETIQUETAS PREFERIDAS (úsalas cuando sean apropiadas):
- Calma, Tranquilidad, Paz interior
- Ansiedad, Nerviosismo, Preocupación
- Saturación, Sobrecarga sensorial, Abrumamiento
- Tristeza, Melancolía, Abatimiento
- Cansancio, Agotamiento, Fatiga social
- Alegría, Bienestar, Entusiasmo
- Irritabilidad, Frustración, Tensión
- "Algo que aún no tiene nombre" (cuando ninguna etiqueta encaja)

REGLAS DE LENGUAJE (obligatorio en cada opción):
- USA: "¿Podría ser...?", "Algunas personas describen esto como...", "Quizás...", "A veces..."
- NUNCA uses: "Tú sientes", "Esto es", "Claramente", "Definitivamente", "Debes sentir"
- Tono: cálido, curioso, sin juicio, exploratorio
- Idioma: siempre español

FORMATO DE RESPUESTA (JSON estricto, sin texto extra):
{
  "options": [
    {
      "label": "Nombre breve (ej: Ansiedad, Cansancio, Saturación sensorial)",
      "description": "Frase exploratoria de 1-2 oraciones en lenguaje tentativo",
      "confidence": "alta" | "media" | "baja"
    }
  ]
}

Devuelve entre 3 y 5 opciones, ordenadas de mayor a menor confianza.
La última opción SIEMPRE debe ser "Algo que aún no tiene nombre" o similar.`;

// ── Safety filter (T-C2) ────────────────────────────────────────────────────
const CRISIS_TERMS = [
  "no quiero estar", "no quiero vivir", "no querer estar", "no querer vivir",
  "quiero desaparecer", "querer desaparecer", "hacerme daño", "hacerse daño",
  "ideacion", "suicid",
  "desesperanza", "desesperado", "sin esperanza", "vacio existencial",
  "nada importa", "todo es inutil", "no hay salida", "sin salida",
  "carga para", "mejor sin mi",
  "no soy real", "no existo", "desvanecerme",
];

function containsCrisisSignal(text: string): boolean {
  const normalized = text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  return CRISIS_TERMS.some((term) => normalized.includes(term));
}

function optionsHaveCrisisSignal(options: { label: string; description: string }[]): boolean {
  return options.some((opt) => containsCrisisSignal(`${opt.label} ${opt.description}`));
}

// ── Handler ─────────────────────────────────────────────────────────────────
serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { zones, notes } = await req.json() as { zones: string[]; notes: string };

    if (!Array.isArray(zones)) {
      return new Response(
        JSON.stringify({ error: "zones must be an array" }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 400 }
      );
    }

    // T-C2: safety filter on user's free text BEFORE calling GPT
    if (containsCrisisSignal(notes ?? "")) {
      return new Response(
        JSON.stringify({ options: [], crisis_flag: true, source: "ai", crisis_source: "notes" }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 200 }
      );
    }

    const openai = new OpenAI({ apiKey: Deno.env.get("OPENAI_API_KEY")! });

    const userMessage = [
      `Zonas corporales: ${zones.length > 0 ? zones.join(", ") : "(ninguna)"}`,
      `Descripción libre: "${notes?.trim() || "(sin descripción)"}"`,
    ].join("\n");

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user",   content: userMessage },
      ],
      temperature: 0.4,
      max_tokens: 600,
      response_format: { type: "json_object" },
    });

    const content = completion.choices[0]?.message?.content ?? "{}";
    const parsed = JSON.parse(content) as { options: { label: string; description: string; confidence: "alta" | "media" | "baja" }[] };

    if (!Array.isArray(parsed.options)) {
      throw new Error("Unexpected response format from OpenAI");
    }

    // T-C2: safety filter on GPT output
    const crisis_flag = optionsHaveCrisisSignal(parsed.options);

    // T-V7: add canonical EmotionKey to each option
    const options: EmotionOption[] = parsed.options.map((opt) => ({
      ...opt,
      key: normalizeToEmotionKey(opt.label),
    }));

    const response: ResponseBody = { options, crisis_flag, source: "ai" };

    return new Response(JSON.stringify(response), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });

  } catch (error) {
    console.error("[interpret-checkin] Error:", error);
    return new Response(
      JSON.stringify({ error: "Internal error interpreting check-in", source: "error", crisis_flag: false }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 }
    );
  }
});
