/**
 * reflect.tsx — S12: AI Interpretation (Check-in)
 *
 * Third screen of the check-in flow. Shows a brief loader then presents
 * 3–5 emotion options generated by the AI (interpret-checkin Edge Function).
 *
 * Flow: S11 (notes) → S12 → S13 (result)
 *
 * T-V3 (2026-03-10): Emotion cards now adopt EmotionColors[key].bg as
 * background when selected, with a dot-colored 1.5px border and an 8px
 * accent circle indicator. Press animation: scale 0.97→1.0 (100ms).
 *
 * Spanish label → EmotionKey mapping is done client-side here until T-V7
 * (Aibus) normalizes the Edge Function output to return proper EmotionKeys.
 *
 * Tone of options (REQUIRED — see BACKEND_STRUCTURE.md §5):
 *   ✅ "¿Podría ser...?", "Algunas personas describen esto como..."
 *   ❌ "Tú sientes", "Esto es", "Claramente"
 */
import React, { useState, useEffect, useRef, useCallback } from "react";
import {
  View,
  ScrollView,
  ActivityIndicator,
  Pressable,
  Animated,
  useColorScheme,
  AccessibilityInfo,
} from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { SafeScreen, Typography, Button, TextInput } from "@/components/ui";
import { ZoneId } from "@/components/body-map/BodyMap";
import { supabase } from "@/lib/supabase";
import {
  getEmotionColors,
  EmotionKey,
  toEmotionKey,
} from "@/constants/colors";

// ── useReduceMotion (same pattern as protocol.tsx — Reanimated v4 workaround) ──
function useReduceMotion(): boolean {
  const [shouldReduce, setShouldReduce] = useState(false);
  useEffect(() => {
    AccessibilityInfo.isReduceMotionEnabled().then(setShouldReduce);
    const sub = AccessibilityInfo.addEventListener("reduceMotionChanged", setShouldReduce);
    return () => sub.remove();
  }, []);
  return shouldReduce;
}

// ── Tipos ──────────────────────────────────────────────────────────────────
type EmotionOption = {
  label: string;
  description: string;
  confidence: "alta" | "media" | "baja";
};

/**
 * Estado del fetch de opciones de emoción.
 * T-U2: distinguir "ai" vs "mock" vs "error" para mostrar feedback correcto.
 */
type FetchSource = "ai" | "mock" | "error";

// ── Mock fallback ──────────────────────────────────────────────────────────
/**
 * Mock de opciones — se usa cuando la Edge Function no está disponible.
 * Simula lo que devolvería GPT-4o-mini con el system prompt de TEA.
 */
function getMockOptions(_zones: ZoneId[], _notes: string): EmotionOption[] {
  return [
    {
      label: "Ansiedad",
      description:
        "¿Podría ser una sensación de alerta o tensión anticipatoria? Algunas personas la notan en el pecho o el estómago.",
      confidence: "alta",
    },
    {
      label: "Cansancio",
      description:
        "Algunas personas describen esto como agotamiento físico o mental acumulado — el cuerpo pide un descanso.",
      confidence: "media",
    },
    {
      label: "Incomodidad",
      description:
        "¿Podría ser que el ambiente o la situación no se siente del todo cómoda? A veces el cuerpo lo registra antes que la mente.",
      confidence: "media",
    },
    {
      label: "Sobrecarga sensorial",
      description:
        "Cuando hay demasiados estímulos, el cuerpo a veces responde así. ¿Podría haber mucho ruido, luz o movimiento cerca?",
      confidence: "baja",
    },
    {
      label: "Algo que aún no tiene nombre",
      description:
        "Quizás lo que sientes no encaja exactamente en ninguna categoría, y eso es completamente válido.",
      confidence: "baja",
    },
  ];
}

/**
 * Resultado del fetch de opciones de emoción.
 * T-U2: devuelve la fuente para que el componente muestre feedback correcto.
 * T-C2: incluye crisis_flag para escalar a flujo de rescate si aplica.
 */
type FetchResult = {
  options: EmotionOption[];
  source: FetchSource;
  crisis_flag: boolean;
};

/**
 * Llama a la Edge Function interpret-checkin con fallback a mock.
 * T-U2: siempre indica la fuente real (ai/mock/error) — no falla silenciosamente.
 * T-C2: propaga crisis_flag si la Edge Function lo detectó.
 */
async function fetchEmotionOptions(
  zones: ZoneId[],
  notes: string
): Promise<FetchResult> {
  try {
    const { data, error } = await supabase.functions.invoke(
      "interpret-checkin",
      { body: { zones, notes } }
    );

    if (error) {
      console.warn("[Reflect] Edge Function error, usando mock:", error.message);
      return { options: getMockOptions(zones, notes), source: "mock", crisis_flag: false };
    }

    // T-C2: si crisis_flag = true y no hay opciones, redirigir a rescate
    if (data?.crisis_flag === true && (!data.options || data.options.length === 0)) {
      return { options: [], source: "ai", crisis_flag: true };
    }

    // Validar formato de respuesta
    if (data?.options && Array.isArray(data.options) && data.options.length > 0) {
      return {
        options: data.options,
        source: data.source === "ai" ? "ai" : "mock",
        crisis_flag: data.crisis_flag === true,
      };
    }

    console.warn("[Reflect] Formato inesperado, usando mock");
    return { options: getMockOptions(zones, notes), source: "mock", crisis_flag: false };

  } catch (e) {
    console.warn("[Reflect] Error de red:", e);
    // T-U2: "error" indica fallo real de red — no falla silenciosamente
    return { options: getMockOptions(zones, notes), source: "error", crisis_flag: false };
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// EmotionCard — T-V3
// ─────────────────────────────────────────────────────────────────────────────

interface EmotionCardProps {
  option:      EmotionOption;
  isSelected:  boolean;
  onSelect:    () => void;
  reduceMotion: boolean;
}

/**
 * EmotionCard — individual tappable emotion option in S12.
 *
 * T-V3 visual spec (FRONTEND_GUIDELINES §12.2):
 *   - Selected bg: EmotionColors[key].bg (soft, calm color)
 *   - Selected border: 1.5px EmotionColors[key].dot
 *   - Selected: 8px accent circle (EmotionColors[key].dot) top-right
 *   - Press animation: scale 0.97→1.0, 100ms
 *   - Reduce motion: skip scale animation, keep all other visual changes
 */
function EmotionCard({ option, isSelected, onSelect, reduceMotion }: EmotionCardProps) {
  // B-DM: resolve dark-aware palette — EmotionColors are light-only
  const colorScheme = useColorScheme();
  const emotionKey  = toEmotionKey(option.label);
  const colors      = getEmotionColors(emotionKey, colorScheme);

  // Scale animation — 0.97 on press, 1.0 on release (100ms each)
  const scale = useRef(new Animated.Value(1)).current;

  const handlePressIn = useCallback(() => {
    if (reduceMotion) return;
    Animated.timing(scale, {
      toValue: 0.97,
      duration: 80,
      useNativeDriver: true,
    }).start();
  }, [scale, reduceMotion]);

  const handlePressOut = useCallback(() => {
    if (reduceMotion) return;
    Animated.timing(scale, {
      toValue: 1,
      duration: 100,
      useNativeDriver: true,
    }).start();
  }, [scale, reduceMotion]);

  return (
    <Animated.View style={{ transform: [{ scale }] }}>
      <Pressable
        onPress={onSelect}
        onPressIn={handlePressIn}
        onPressOut={handlePressOut}
        accessibilityRole="button"
        accessibilityState={{ selected: isSelected }}
        accessibilityLabel={`${option.label}: ${option.description}`}
        style={[
          {
            borderRadius: 24,
            padding: 20,
            // Selected: emotion background color. Unselected: transparent (let NW class handle it)
            backgroundColor: isSelected ? colors.bg : undefined,
            borderWidth: 1.5,
            borderColor: isSelected ? colors.dot : "#E0DDD8", // script-border fallback
          },
        ]}
        className={
          isSelected
            ? "" // background handled by inline style above
            : "bg-script-bg-secondary dark:bg-script-dark-secondary"
        }
      >
        {/* Selected indicator — 8px accent circle (top-right) */}
        {isSelected && (
          <View
            style={{
              position: "absolute",
              top: 14,
              right: 14,
              width: 8,
              height: 8,
              borderRadius: 4,
              backgroundColor: colors.dot,
            }}
          />
        )}

        <Typography variant="headingS">{option.label}</Typography>
        <Typography
          variant="caption"
          className="text-script-text-secondary dark:text-script-dark-text-secondary mt-1"
          style={isSelected ? { color: colors.text } : undefined}
        >
          {option.description}
        </Typography>
      </Pressable>
    </Animated.View>
  );
}

// ── Main Component ─────────────────────────────────────────────────────────
export default function CheckinReflectScreen() {
  const router = useRouter();
  const isDark = useColorScheme() === "dark";
  const reduceMotion = useReduceMotion();
  const spinnerColor = isDark ? "#5A7E92" : "#A8C5DA";

  const { zones: zonesParam, notes: notesParam } = useLocalSearchParams<{
    zones: string;
    notes: string;
  }>();

  const [isLoading, setIsLoading] = useState(true);
  const [options, setOptions] = useState<EmotionOption[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const [showCustomInput, setShowCustomInput] = useState(false);
  const [customEmotion, setCustomEmotion] = useState("");
  // T-U2: fuente de la respuesta para feedback visible al usuario
  const [fetchSource, setFetchSource] = useState<FetchSource>("ai");

  const confirmedEmotion = showCustomInput ? customEmotion.trim() : selected;

  // Llamar a Edge Function (con fallback a mock) al montar
  useEffect(() => {
    const zones = (zonesParam?.split(",").filter(Boolean) ?? []) as ZoneId[];
    const notes = notesParam ?? "";

    fetchEmotionOptions(zones, notes).then((result) => {
      // T-C2: si hay crisis_flag, redirigir al flujo de rescate inmediatamente
      if (result.crisis_flag) {
        router.replace("/(app)/rescue/assess");
        return;
      }
      setOptions(result.options);
      setFetchSource(result.source);
      setIsLoading(false);
    });
  }, [zonesParam, notesParam]);

  const handleContinue = () => {
    if (!confirmedEmotion) return;
    // replace instead of push — prevents stale state when user re-opens check-in tab
    router.replace({
      pathname: "/(app)/checkin/result",
      params: {
        zones: zonesParam ?? "",
        notes: notesParam ?? "",
        emotion: confirmedEmotion,
      },
    });
  };

  // ── Estado de carga ──────────────────────────────────────────────────────
  if (isLoading) {
    return (
      <SafeScreen>
        <View className="flex-1 items-center justify-center gap-6 px-5">
          <ActivityIndicator size="large" color={spinnerColor} />
          <Typography
            variant="body"
            className="text-center text-script-text-secondary dark:text-script-dark-text-secondary"
          >
            Conectando los puntos...
          </Typography>
        </View>
      </SafeScreen>
    );
  }

  // ── Pantalla principal ───────────────────────────────────────────────────
  return (
    <SafeScreen>
      <ScrollView
        contentContainerStyle={{ flexGrow: 1 }}
        showsVerticalScrollIndicator={false}
      >
        <View className="flex-1 px-5 pt-6 pb-8 gap-5">
          <View className="gap-2">
            <Typography variant="headingL">
              ¿Podría ser algo de esto?
            </Typography>
            <Typography
              variant="body"
              className="text-script-text-secondary dark:text-script-dark-text-secondary"
            >
              No son diagnósticos — son posibilidades. Elige la que más resuene.
            </Typography>
          </View>

          {/* T-U2: feedback visible cuando la respuesta es aproximada o falló */}
          {fetchSource === "mock" && (
            <View className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-700 rounded-xl px-4 py-3">
              <Typography
                variant="caption"
                className="text-yellow-800 dark:text-yellow-200"
              >
                💡 Estas opciones son aproximadas — la interpretación personalizada no está disponible en este momento.
              </Typography>
            </View>
          )}
          {fetchSource === "error" && (
            <View className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-700 rounded-xl px-4 py-3">
              <Typography
                variant="caption"
                className="text-red-800 dark:text-red-200"
              >
                ⚠️ No se pudo conectar al servicio de interpretación. Las opciones que ves son generales, no personalizadas para tu check-in de hoy.
              </Typography>
            </View>
          )}

          {/* T-V3: emotion cards with color, accent circle, and scale animation */}
          <View className="gap-3">
            {options.map((option) => (
              <EmotionCard
                key={option.label}
                option={option}
                isSelected={selected === option.label}
                onSelect={() => {
                  setSelected(option.label);
                  setShowCustomInput(false);
                }}
                reduceMotion={reduceMotion}
              />
            ))}
          </View>

          {!showCustomInput ? (
            <Button
              title="Ninguna de estas"
              variant="ghost"
              onPress={() => {
                setShowCustomInput(true);
                setSelected(null);
              }}
            />
          ) : (
            <View className="gap-3">
              <Typography variant="body">¿Cómo lo llamarías tú?</Typography>
              <TextInput
                value={customEmotion}
                onChangeText={setCustomEmotion}
                placeholder="Escribe con tus propias palabras..."
                accessibilityLabel="Describe la emoción con tus propias palabras"
              />
              <Button
                title="← Ver opciones"
                variant="ghost"
                onPress={() => setShowCustomInput(false)}
              />
            </View>
          )}

          <View className="flex-1" />

          <Button
            title="Continuar →"
            onPress={handleContinue}
            variant="primary"
            disabled={!confirmedEmotion}
          />
        </View>
      </ScrollView>
    </SafeScreen>
  );
}
