/**
 * lib/supabase.ts — Supabase client for Script
 *
 * Uses the anon key for public queries (predefined scripts, etc.).
 * For RLS-protected operations, the client needs a valid JWT configured
 * via setSupabaseToken() (B-51 v2 — Admin API approach).
 *
 * Why autoRefreshToken: false?
 *   We use Privy as the auth provider, not Supabase Auth.
 *   The Supabase refresh token does not apply here — the session token is
 *   established via sync-privy-user (generateLink + verifyOtp) on every app start
 *   when a Privy session exists. See AuthGate in _layout.tsx and handlePostLogin in auth.tsx.
 *
 * Session storage:
 *   Supabase stores the session token in our storage adapter (SecureStore on native,
 *   localStorage on web). On next launch, Supabase restores it automatically
 *   if not expired — no extra network call needed.
 */
import { createClient } from "@supabase/supabase-js";
import * as SecureStore from "expo-secure-store";
import { Platform } from "react-native";

/**
 * Storage adapter for the Supabase session.
 *
 * Android/iOS: SecureStore (device-encrypted).
 * Web: localStorage (Expo dev tools runs a web server in parallel;
 *      SecureStore is not available there and throws getValueWithKeyAsync errors).
 *
 * This distinction is required because `npx expo start` bundles for web too,
 * even though the app is mobile-only.
 */
const storage = Platform.OS === "web"
  ? {
      // Web fallback — only used in Expo dev tools, not in production
      getItem: (key: string) =>
        Promise.resolve(
          typeof localStorage !== "undefined" ? localStorage.getItem(key) : null
        ),
      setItem: (key: string, value: string) => {
        if (typeof localStorage !== "undefined") localStorage.setItem(key, value);
        return Promise.resolve();
      },
      removeItem: (key: string) => {
        if (typeof localStorage !== "undefined") localStorage.removeItem(key);
        return Promise.resolve();
      },
    }
  : {
      // Native (Android/iOS) — encrypted SecureStore
      getItem:    (key: string) => SecureStore.getItemAsync(key),
      setItem:    (key: string, value: string) => SecureStore.setItemAsync(key, value),
      removeItem: (key: string) => SecureStore.deleteItemAsync(key),
    };

const supabaseUrl     = process.env.EXPO_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage,
    // autoRefreshToken: false — Privy manages the session lifecycle.
    // sync-privy-user generates a new token on each app launch via
    // generateLink + verifyOtp. We don't want Supabase attempting
    // automatic refresh (it could try to use old/invalid tokens from SecureStore).
    autoRefreshToken:  false,
    persistSession:     true,  // Session persists in SecureStore across app restarts
    detectSessionInUrl: false,
  },
});

/**
 * setSupabaseToken — Activates a Supabase session using the OTP token hash
 * returned by sync-privy-user via the Admin API.
 *
 * B-51 v2 (Admin API approach):
 *   sync-privy-user returns `otp_token_hash` generated by:
 *     auth.admin.generateLink({ type: 'magiclink', email })
 *
 *   Calling verifyOtp with that hash produces a real Supabase Auth session:
 *   - Valid access_token signed by Supabase (not by us)
 *   - refresh_token for auto-renewal
 *   - auth.uid() returns the user's UUID → RLS policies resolve correctly
 *
 *   No SUPABASE_JWT_SECRET required — the Admin API handles everything internally.
 *
 * B-60 FIX: type must be 'magiclink', NOT 'email'.
 *   generateLink({ type: 'magiclink' }) produces a token that must be verified
 *   with the matching type. Using 'email' caused a silent session failure:
 *   verifyOtp returned an error, session was never established, and RLS
 *   remained broken — with no visible error shown to the user.
 *
 * @param tokenHash - hashed_token from the Admin API generateLink response
 */
export async function setSupabaseToken(tokenHash: string): Promise<void> {
  try {
    const { data, error } = await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type: "magiclink", // B-60 FIX: must match generateLink({ type: 'magiclink' })
    });
    if (error) throw error;
    if (!data.session) throw new Error("verifyOtp returned no session");
    console.log("[Supabase] Session activated via verifyOtp — RLS enabled");
  } catch (e) {
    // Non-critical — app works without RLS in degraded mode (public scripts still load)
    console.warn("[Supabase] Error activating session:", e);
  }
}
